version: '3.9'
services:    

  app:
    volumes: []
    command: [/start.sh]

  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: integration
    image: integration
    depends_on:
      - app
    
