version: '3.9'
services:

  app:
    build: .
    env_file: .env
    container_name: app
    image: app
    environment:
      SQL_URL: "/db/sso.db"
    volumes:
      - sqlite-data:/db
    ports:
      - 9000:9000
    
volumes:
  sqlite-data: